language: python
sudo: required
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - "pip install ."
  - "pip install pytest"
# command to run tests
script: py.test -rsx -v
