language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - "pip install -U pip"
  - "pip install '.[dev,test]'"
# command to run tests
script: py.test -rsx -v
